[package]
name = "tony1-dev/configify"
version = "0.1.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
